# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: On Push
on: [push]
permissions:
  contents: write

jobs:
  build:
    name: Build and Release Preview
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build Gradle Project
        run: ./gradlew build
      - name: Read Version Name
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./update/VERSION
      - name: Get Short Commit Hash
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Upload Files to Release
        uses: svenstaro/upload-release-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*
          tag: indev-${{steps.version.outputs.content}}-build-${{steps.sha.outputs.sha_short}}
          release_name: Version ${{ steps.version.outputs.content}}
          prerelease: true
          make_latest: false
          overwrite: true
          file_glob: true