name: Release
on: [workflow_dispatch]
permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build Gradle Project
        run: ./gradlew build
      - name: Read Version Name
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./update/VERSION
      - name: Read Loader Name
        id: loader
        uses: juliangruber/read-file-action@v1
        with:
          path: ./update/LOADER
      - name: Read Minecraft Version
        id: minecraft
        uses: juliangruber/read-file-action@v1
        with:
          path: ./update/MINECRAFT_VERSION
      - name: Read Changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./update/CHANGELOG.md
      - name: Upload Files to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*
          tag: ${{ steps.version.outputs.content }}-${{ steps.loader.outputs.content }}-${{ steps.minecraft.outputs.content }}
          release_name: Version ${{ steps.version.outputs.content }} for ${{ steps.loader.outputs.content }} ${{ steps.minecraft.outputs.content }}
          overwrite: true
          file_glob: true
          body: |
            ${{ steps.changelog.outputs.content }}