# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: On tag pushed
on:
  push:
    tags:
      - '**'
      - '!indev**'
permissions:
  contents: write

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-24.04
    if: startsWith(github.ref_name, 'indev') == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build gradle project
        run: ./gradlew build
      - name: Read version name
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION
      - name: Read Changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./update/CHANGELOG.md
      - name: Get short commit hash
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Upload files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*
          tag: ${{ github.ref_name }}
          release_name: Version ${{ steps.version.outputs.content}}
          overwrite: true
          file_glob: true
          body: |
            ${{ steps.changelog.outputs.content }}